// SPDX-License-Identifier: GPL-3.0-or-later
export const ACTIVE=new Set(['submitting','checking','downloading','converting']);
export const FINISHED=new Set(['ready','error','cancelled','expired']);
export const defaults={format:'mp4',engine:'auto',resolution:1080,bitrate:192,fps:60,playlist:false,max_items:10,subtitles:false,automatic_subtitles:false,subtitle_language:'es',thumbnail:false,metadata:true,description:false,hardware:false,rate_limit:0,retries:2};
const enums={format:['mp3','m4a','wav','flac','opus','ogg','mp4','mkv','webm','both','gallery'],engine:['auto','yt-dlp','gallery-dl','spotdl'],resolution:[480,720,1080,1440,2160],bitrate:[128,192,256,320],fps:[30,60],subtitle_language:['es','en','es,en']};
export function normalizeOptions(raw={}){const result={...defaults};for(const key in defaults){if(enums[key]){if(enums[key].includes(raw[key]))result[key]=raw[key];}else if(typeof defaults[key]==='boolean'){if(typeof raw[key]==='boolean')result[key]=raw[key];}else if(Number.isInteger(raw[key]))result[key]=Math.max(key==='max_items'?1:0,Math.min(key==='max_items'?20:key==='retries'?5:10000,raw[key]));}return result;}
export function parseLinks(text){const valid=[],invalid=[];for(const value of String(text).split(/\s+/).filter(Boolean)){try{const url=new URL(value);if(!['http:','https:'].includes(url.protocol)||url.username||url.password||value.length>2048)throw Error();url.hash='';valid.push(url.href);}catch{invalid.push(value);}}return {valid,invalid};}
export function effectiveOptions(url, options){const o=normalizeOptions(options),host=new URL(url).hostname;const spotify=host==='spotify.com'||host.endsWith('.spotify.com')||host==='spotify.link';if(o.engine==='auto'&&spotify){o.engine='spotdl';}if(o.format==='gallery'&&o.engine==='auto')o.engine='gallery-dl';return o;}
export function importQueue(text){const parsed=JSON.parse(text);if(parsed?.version!==1||!Array.isArray(parsed.items))throw Error('El JSON no es una cola de Off The Wall.');return parsed.items.slice(0,100).map(item=>{const {valid,invalid}=parseLinks(item.url);if(valid.length!==1||invalid.length)throw Error('El archivo contiene un enlace no válido.');return {url:valid[0],options:effectiveOptions(valid[0],item.options)};});}
