// SPDX-License-Identifier: GPL-3.0-or-later
import {DOWNLOAD_API} from './downloader-config.js';
import {ACTIVE,FINISHED,normalizeOptions,parseLinks,effectiveOptions,importQueue} from './download-model.js';
const $=id=>document.getElementById(id),api=DOWNLOAD_API.replace(/\/$/,''),storageKey='otw-download-queue-v2';
const fields={format:'linkFormat',engine:'linkEngine',resolution:'linkResolution',bitrate:'linkBitrate',fps:'linkFps',playlist:'linkPlaylist',max_items:'linkMaxItems',subtitles:'linkSubtitles',automatic_subtitles:'linkAutoSubs',subtitle_language:'linkLanguage',thumbnail:'linkThumbnail',metadata:'linkMetadata',description:'linkDescription',hardware:'linkHardware',rate_limit:'linkRate',retries:'linkRetries'};
const labels={waiting:'En espera',submitting:'Conectando',checking:'Comprobando',downloading:'Descargando',converting:'Convirtiendo',ready:'Lista',error:'Error',cancelled:'Cancelada',expired:'Caducada'};
let items=[],connected=false,paused=true,pumping=false,polling=false,capabilities=null,timer=null;
function say(text,error=false){$('linkStatus').textContent=text;$('linkStatus').classList.toggle('error',error);}
function options(){const raw={};for(const [key,id] of Object.entries(fields)){const el=$(id);raw[key]=el.type==='checkbox'?el.checked:el.type==='number'||['resolution','bitrate','fps'].includes(key)?Number(el.value):el.value;}return normalizeOptions(raw);}
function applyOptions(raw){for(const [key,value] of Object.entries(normalizeOptions(raw))){const el=$(fields[key]);if(el.type==='checkbox')el.checked=value;else el.value=String(value);}}
function save(){try{if($('rememberQueue').checked)localStorage.setItem(storageKey,JSON.stringify({options:options(),items:items.map(({id,url,options,state,remote,title,message,result_ext,progress,created,count})=>({id,url,options,state,remote,title,message,result_ext,progress,created,count}))}));else localStorage.removeItem(storageKey);}catch{say('El navegador no permite guardar la cola. Puedes exportarla como JSON.',true);}}
function restore(){try{const stored=JSON.parse(localStorage.getItem(storageKey)||'null');if(!stored)return;$('rememberQueue').checked=true;applyOptions(stored.options);for(const value of (stored.items||[]).slice(0,100)){const parsed=parseLinks(value.url);if(parsed.valid.length!==1||parsed.invalid.length)continue;items.push({...value,id:crypto.randomUUID(),url:parsed.valid[0],options:effectiveOptions(parsed.valid[0],value.options),state:ACTIVE.has(value.state)&&!value.remote?'waiting':labels[value.state]?value.state:'waiting',remote:/^[A-Za-z0-9_-]{30,60}$/.test(value.remote||'')?value.remote:null,title:String(value.title||'').slice(0,200)});}}catch{say('No se pudo restaurar la cola guardada.',true);}for(const item of items)if(ACTIVE.has(item.state)&&!item.remote)item.state='waiting';}
async function request(path,method='GET',body){const response=await fetch(api+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(120000),cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer'});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(typeof data.detail==='string'?data.detail:`Error del servidor (${response.status}).`);error.status=response.status;throw error;}return data;}
function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function button(text,action,id){const el=element('button',text,'reset');el.type='button';el.dataset.action=action;el.dataset.id=id;return el;}
function visibleItems(){const query=$('queueSearch').value.toLowerCase(),filter=$('queueFilter').value;let result=items.filter(i=>(!query||(i.title+' '+i.url).toLowerCase().includes(query))&&(filter==='all'||filter==='active'&&ACTIVE.has(i.state)||filter==='error'&&['error','cancelled','expired'].includes(i.state)||i.state===filter));const sort=$('queueSort').value;return result.sort((a,b)=>sort==='title'?(a.title||a.url).localeCompare(b.title||b.url):sort==='newest'?b.created-a.created:a.created-b.created);}
function render(){
 const focused=document.activeElement?.dataset;const focus=focused?.action?{...focused}:null;
 $('queueTotal').textContent=items.length;$('queueActive').textContent=items.filter(i=>ACTIVE.has(i.state)).length;$('queueReady').textContent=items.filter(i=>i.state==='ready').length;$('queueErrors').textContent=items.filter(i=>i.state==='error').length;
 $('startQueue').disabled=!api||!connected||!items.some(i=>i.state==='waiting');$('pauseQueue').disabled=paused;
 $('serverBadge').textContent=!api?'Próximamente':connected?'Descargas disponibles':'Servicio no disponible';$('queueNotice').textContent=paused?'Cola en pausa. Los trabajos que ya están procesando continúan.':'Cola en marcha. Los archivos estarán disponibles durante 30 minutos al finalizar.';
 const container=$('downloadQueue');container.replaceChildren();const visible=visibleItems();$('queueEmpty').hidden=!!visible.length;$('queueEmpty').textContent=items.length?'No hay elementos con ese filtro.':'Tu próxima descarga empieza con un enlace.';
 for(const item of visible){const card=element('article',undefined,'download-card');const heading=element('div',undefined,'download-card-heading');heading.append(element('strong',item.title||new URL(item.url).hostname),element('span',labels[item.state]||item.state,'download-state state-'+item.state));card.append(heading,element('p',item.url,'download-url'),element('p',`${item.options.engine} · ${item.options.format.toUpperCase()}${item.options.playlist?' · lista':''}`,'converter-note'));const progress=element('progress');progress.max=100;progress.setAttribute('aria-label','Progreso de '+(item.title||'descarga'));if(Number.isFinite(item.progress))progress.value=item.progress;else if(!ACTIVE.has(item.state))progress.value=item.state==='ready'?100:0;card.append(progress,element('p',item.message||'Lista para iniciar.','download-message'));if(item.speed||item.eta)card.append(element('small',`${item.speed?`${(item.speed/1024).toFixed(0)} KB/s`:''}${item.eta?` · ${Math.round(item.eta)} s estimados`:''}`,'converter-note'));const actions=element('div',undefined,'queue-tools');if(item.state==='ready'&&item.remote){const link=element('a','Descargar '+(item.result_ext||item.options.format).toUpperCase(),'download-result');link.href=`${api}/files/${encodeURIComponent(item.remote)}`;link.referrerPolicy='no-referrer';actions.append(link);}if(item.state==='waiting'){actions.append(button('Priorizar','priority',item.id),button('Quitar','remove',item.id));}if(ACTIVE.has(item.state)&&item.remote){actions.append(button('Cancelar','cancel',item.id));}if(FINISHED.has(item.state)){actions.append(button('Reintentar','retry',item.id),button('Quitar','remove',item.id));}card.append(actions);container.append(card);}
 if(focus){const el=[...container.querySelectorAll('button')].find(b=>b.dataset.id===focus.id&&b.dataset.action===focus.action);el?.focus({preventScroll:true});}
 save();
}
function append(entries){let added=0,duplicates=0;for(const entry of entries){if(items.length>=100)break;if($('skipDuplicates').checked&&items.some(i=>i.url===entry.url)){duplicates++;continue;}items.push({id:crypto.randomUUID(),url:entry.url,options:effectiveOptions(entry.url,entry.options||options()),state:'waiting',created:Date.now()+added,title:'',message:'En espera.'});added++;}render();say(`${added} enlace(s) añadido(s).${duplicates?` ${duplicates} repetido(s) omitido(s).`:''}${items.length>=100?' La cola alcanzó su límite de 100.':''}`);if($('autoQueue').checked&&connected){paused=false;pump();}return added;}
async function pump(){if(pumping||paused||!connected)return;pumping=true;try{const max=Math.min(Number($('queueConcurrency').value),capabilities?.max_parallel||2);while(!paused&&connected&&items.filter(i=>ACTIVE.has(i.state)).length<max){const item=items.find(i=>i.state==='waiting');if(!item)break;item.state='submitting';item.message='Enviando enlace…';render();try{const result=await request('/jobs','POST',{url:item.url,...item.options});item.remote=result.id;item.state='checking';item.message='Comprobando enlace…';}catch(error){item.state=error.status===429?'waiting':'error';item.message=error.message;if(error.status===401){connected=false;paused=true;}if(error.status===429){paused=true;say('El servidor está ocupado. Espera y pulsa Iniciar cola para continuar.',true);}}render();}}finally{pumping=false;schedule();}}
function schedule(){clearTimeout(timer);if(connected&&items.some(i=>ACTIVE.has(i.state)&&i.remote))timer=setTimeout(poll,2000);}
async function poll(){if(polling||!connected)return;polling=true;try{await Promise.all(items.filter(i=>ACTIVE.has(i.state)&&i.remote).map(async item=>{try{const data=await request('/jobs/'+encodeURIComponent(item.remote));if(!ACTIVE.has(item.state))return;Object.assign(item,{state:data.state,message:data.message,title:data.title||item.title,progress:data.progress,result_ext:data.result_ext,count:data.count,speed:data.speed,eta:data.eta});if(data.state==='ready')downloadAutomatically(item);}catch(error){if(error.status===404){item.state='expired';item.message='El trabajo caducó o el servidor se reinició. Puedes reintentarlo.';}else if(error.status===401){connected=false;paused=true;say('El servicio no está disponible. Vuelve a intentarlo más tarde.',true);}else item.message='Conexión interrumpida. Volveremos a comprobar el trabajo.';}}));render();}finally{polling=false;await pump();schedule();}}
$('linkDownloadForm').addEventListener('submit',event=>{event.preventDefault();const {valid,invalid}=parseLinks($('platformUrls').value);if(invalid.length){say(`Hay ${invalid.length} enlace(s) no válido(s). Usa un enlace HTTP o HTTPS por línea.`,true);return;}if(!valid.length){say('Pega al menos un enlace.',true);return;}append(valid.map(url=>({url})));$('platformUrls').value='';});
async function connectService(){if(!api)return;say('Preparando descargas… El primer inicio puede tardar hasta dos minutos.');try{capabilities=await request('/capabilities');connected=true;say('Pega tus enlaces, elige el formato y pulsa Descargar archivos.');await poll();}catch{say('El servicio de descarga no está disponible ahora. Puedes preparar tu cola y volver a intentar más tarde.',true);}finally{render();}}
const autoDownloads=[];let saving=false;
function downloadAutomatically(item){autoDownloads.push(item);saveNext();}
function saveNext(){if(saving||!autoDownloads.length)return;saving=true;const item=autoDownloads.shift();const link=document.createElement('a');link.href=`${api}/files/${encodeURIComponent(item.remote)}`;link.referrerPolicy='no-referrer';link.download=`archivo.${item.result_ext||item.options.format}`;link.target='otw-download-frame';link.hidden=true;document.body.append(link);link.click();link.remove();say('Archivo preparado en el formato elegido. Si el navegador bloquea la descarga automática, pulsa Descargar en su tarjeta.');setTimeout(()=>{saving=false;saveNext();},1500);}
const downloadFrame=document.createElement('iframe');downloadFrame.name='otw-download-frame';downloadFrame.hidden=true;downloadFrame.title='Descarga de archivos';document.body.append(downloadFrame);
$('startQueue').addEventListener('click',()=>{paused=false;render();pump();});$('pauseQueue').addEventListener('click',()=>{paused=true;render();});
$('retryQueue').addEventListener('click',()=>{for(const item of items)if(['error','cancelled','expired'].includes(item.state)){Object.assign(item,{state:'waiting',remote:null,progress:null,message:'En espera para reintentar.'});}render();pump();});
$('clearQueue').addEventListener('click',()=>{items=items.filter(i=>!FINISHED.has(i.state));render();});
$('downloadQueue').addEventListener('click',async event=>{const control=event.target.closest('button[data-action]');if(!control)return;const item=items.find(i=>i.id===control.dataset.id);if(!item)return;const action=control.dataset.action;if(action==='remove'&&!ACTIVE.has(item.state))items=items.filter(i=>i!==item);if(action==='retry'&&FINISHED.has(item.state))Object.assign(item,{state:'waiting',remote:null,progress:null,message:'En espera para reintentar.'});if(action==='priority'&&item.state==='waiting'){items=items.filter(i=>i!==item);items.unshift(item);item.created=Math.min(...items.map(i=>i.created))-1;}if(action==='cancel'&&item.remote){control.disabled=true;try{await request('/jobs/'+encodeURIComponent(item.remote),'DELETE');Object.assign(item,{state:'cancelled',message:'Descarga cancelada.',progress:null});}catch(error){say('No se pudo confirmar la cancelación: '+error.message,true);}}render();pump();});
for(const id of ['queueSearch','queueFilter','queueSort'])$(id).addEventListener('input',render);
$('pasteLinks').addEventListener('click',async()=>{try{$('platformUrls').value=await navigator.clipboard.readText();say('Enlaces pegados. Revísalos y pulsa Descargar archivos.');}catch{say('No se pudo leer el portapapeles. Pega los enlaces directamente en el cuadro.',true);$('platformUrls').focus();}});
async function importFile(file){if(!file)return;if(file.size>1024*1024){say('El archivo de enlaces supera 1 MB.',true);return;}try{const text=await file.text();if(file.name.toLowerCase().endsWith('.json'))append(importQueue(text));else{const parsed=parseLinks(text);if(parsed.invalid.length)throw Error('El TXT contiene enlaces no válidos.');append(parsed.valid.map(url=>({url})));}}catch(error){say(error.message,true);}}
$('importLinksButton').addEventListener('click',()=>$('importLinks').click());
$('importLinks').addEventListener('change',async()=>{await importFile($('importLinks').files[0]);$('importLinks').value='';});
for(const name of ['dragover','drop'])$('linkDownloadForm').addEventListener(name,event=>{event.preventDefault();if(name==='drop'){if(event.dataTransfer.files.length){if(event.dataTransfer.files.length!==1){say('Importa un archivo a la vez.',true);return;}importFile(event.dataTransfer.files[0]);}else{$('platformUrls').value=event.dataTransfer.getData('text/plain');}}});
$('exportQueue').addEventListener('click',()=>{const data={version:1,items:items.map(({url,options})=>({url,options}))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const anchor=element('a');anchor.href=url;anchor.download='off-the-wall-cola.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Cola exportada con enlaces y ajustes. No incluye clave ni archivos.');});
for(const id of [...Object.values(fields),'rememberQueue'])$(id).addEventListener('change',()=>{if(id==='linkAutoSubs'&&$(id).checked)$('linkSubtitles').checked=true;if(id==='linkEngine'){if($(id).value==='gallery-dl')$('linkFormat').value='gallery';if($(id).value==='spotdl')$('linkFormat').value='mp3';}$('engineHint').textContent=$('linkEngine').value==='spotdl'?'Spotify aporta los datos; se descarga una coincidencia encontrada en YouTube, que puede ser una versión diferente.':'Los ajustes se aplican a los enlaces que añadas a partir de ahora.';save();});
window.addEventListener('beforeunload',event=>{if(items.some(i=>ACTIVE.has(i.state))){event.preventDefault();event.returnValue='';}});
restore();render();connectService();if(!api)say('La descarga de enlaces aún no está disponible: falta activar el servicio. Puedes preparar tu cola.');
